using System.Collections;
using UnityEngine;



public class Teleport : MonoBehaviour
{
    public GameObject teleport;

    private void OnTriggerStay2D(Collider2D collision)
    {
        if (collision.gameObject.CompareTag("Player"))
        {
            if (Input.GetKeyDown(KeyCode.E))
            {
                StartCoroutine(Portal());
            }
        }
    }
    IEnumerator Portal()
    {
        PlayerMovement.instance.TeleportMinus();

        yield return new WaitForSeconds(1);
        PlayerMovement.instance.transform.position = teleport.transform.position;

        PlayerMovement.instance.TeleportPlus();
    }
}
